### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by gtrefs** [jlink/jqwik-testcontainers#3]
In the Readme a release is referenced which is not yet availble. We should push a release to maven.

**Comment by jlink** [comment]
Challenge accepted

**Comment by jlink** [comment]
Which version should be released? Since the project currently depends on a jqwik snapshot only a snapshot can be released.

**Comment by gtrefs** [comment]
@jlink I see. Would you mind releasing version 1.3.7? It contains the enhancement regarding assumptions and `Examples`. Otherwise, one of the tests won't pass.

**Comment by jlink** [comment]
I target Mon/Tues. Is that early enough?

**Comment by gtrefs** [comment]
Sure :+1:

**Comment by jlink** [comment]
code is ready for release. As soon as I have 30 minutes to spare I'll go ahead.

**Comment by jlink** [comment]
I updated to jqwik 1.3.7. However, I also had to update to testcontainers 1.15.0-rc2 because 1.14.3 is incompatible with the latest docker desktop version on Mac.

Should I go for a release 0.5 anyway?

**Comment by jlink** [comment]
Release 0.5.0 should be available on Maven Central
