### ISSUE TITLE
Start/Stop container once per container class / test run

### ISSUE THREAD

**Issue by jlink** [jlink/jqwik-testcontainers#5]
I'd like to have more control over the lifecycle of a container. As I understand it I can currently determine if a container is started/stopped per property or per try:

`@Container(startPerTry = true)
`

What about having something like:

```
@Container(lifecycle=ContainerLifecycle.PER_TRY)

enum ContainerLifecycle { PER_TRY, PER_PROPERTY, PER_CONTAINER, PER_RUN)
```

### Rationale

Sometime starting/stopping is expensive and there are other ways to clean up, e.g. deleting a table in a database.

### Discussion

Maybe that would require to allow static scope for container variables. But maybe not.

**Comment by gtrefs** [comment]
A container can also just be started for a test run. Have you tried using a
static field in your tests? This use case is also described in the Readme:
https://github.com/jlink/jqwik-testcontainers#standard-usage. Or is it like
you want to know in your test if the container when the container will be
stopped?

Am Freitag, 6. November 2020 schrieb Johannes Link <notifications@github.com

**Comment by jlink** [comment]
The scenario you refer is what I want, except that I don't succeed to make it work in Kotlin.
What I tried is:

```
    companion object {
        @JvmField
        @Container
        val mongoDBContainer = MongoDBContainer(DockerImageName.parse("mongo:4.2.10"))
    }
```

but I get this error message: `MongoDBContainer should be started first`

Any idea?

**Comment by jlink** [comment]
Looks like jqwik-testcontainers does not work in Kotlin at all. A non-static:

```
    @Container
    @JvmField
    val mongoDBContainer = MongoDBContainer(DockerImageName.parse("mongo:4.2.10"))

```

results in the same error. Maybe the way jqwik-testcontainers checks for annotations is incompatible.

**Comment by gtrefs** [comment]
@jlink Maybe you just forgot to add the `@Testcontainers` annotation?
```kotlin
@Testcontainers
class ContainersInKotlinTest {

    @Container
    @JvmField
    val mongoDb = MongoDBContainer(DockerImageName.parse("mongo:4.2.10"))

    @Example
    fun containersAreRunning() {
        assertThat(mongoDb.isRunning).isTrue()
    }
}
```

**Comment by jlink** [comment]
You're right. Thanks @gtrefs!
